from playwright.sync_api import Page


def test_practice_form(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    f_name = page.locator("#firstName")
    f_name.fill('Elon')
    l_name = page.locator("#lastName")
    l_name.fill('Mask')
    email = page.locator('#userEmail')
    email.fill('123abc@gmail.com')
    page.evaluate("window.scrollBy(0, 700);")
    gender = page.locator("//label[contains(.,'Female')]")
    gender.click()
    mobile_num = page.locator('#userNumber')
    mobile_num.fill('8765876586')
    date = page.locator('#dateOfBirthInput')
    date.click()
    year = page.locator("//select[contains(@class,'year-select')]")
    year.click()
    page.select_option("select.react-datepicker__year-select", "1979")
    page.select_option("select.react-datepicker__month-select", "0")
    day = page.locator("//div[contains(@class,'day--022')]")
    day.click()
    subjects = page.locator('#subjectsInput')
    subjects.fill('English')
    subjects.press('Enter')
    hobbies = page.locator("//label[contains(.,'Sports')]")
    hobbies.click()
    hobbies = page.locator("//label[contains(.,'Music')]")
    hobbies.click()
    current_address = page.locator('#currentAddress')
    current_address.fill(' Vladimir Shambaryan 11 Southgate Blvd C25 N11467 New Castle Delaware 19720 USA ')
    select_state = page.locator("(//div[contains(.,'Select State')])[12]")
    select_state.click()
    state = page.locator('#react-select-3-option-0')
    state.click()
    select_city = page.locator("(//div[contains(.,'Select City')])[11]")
    select_city.click()
    city = page.locator('#react-select-4-option-1')
    city.click()
    submit = page.locator('#submit')
    submit.click()
    table_info = page.locator("//div[@class='modal-body']")
    print(table_info.inner_text())
